name: Actualitzar streaming Tarragona

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  actualitzar:

    runs-on: ubuntu-latest

    steps:

      - name: Descarregar repositori
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Instal·lar dependències
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instal·lar Chromium
        run: |
          python -m playwright install chromium
          python -m playwright install-deps chromium

      - name: Capturar streaming
        run: |
          python webcam.py

      - name: Comprovar M3U
        run: |
          echo "Contingut de tarragona.m3u:"
          cat tarragona.m3u

      - name: Actualitzar repositori
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add tarragona.m3u

          if git diff --cached --quiet; then
            echo "No hi ha canvis."
            exit 0
          fi

          git commit -m "Actualitzar streaming Tarragona"

          git push origin HEAD:${GITHUB_REF_NAME}
